### ISSUE TITLE
The Word "legacy"

### ISSUE THREAD

**Issue by odoluca** [jvh/identifying-rhyming-words#1]
Word "legacy" in the INPUT_WORD_LIST breaks the program with following error:

Traceback (most recent call last):
  File "C:/Users/doluc/Downloads/identifying-rhyming-words-master/src/main.py", line 368, in <module>
    best_word, _ = run()
  File "C:/Users/doluc/Downloads/identifying-rhyming-words-master/src/main.py", line 352, in run
    phonetic_list = split_words_into_phonetics([INPUT_WORD] + INPUT_WORD_LIST.copy())
  File "C:/Users/doluc/Downloads/identifying-rhyming-words-master/src/main.py", line 183, in split_words_into_phonetics
    char_in_mod_pos = w[index + len(mod)]
IndexError: string index out of range

Process finished with exit code 1

**Comment by odoluca** [comment]
Word "Citizenry" also returns the same error.

**Comment by odoluca** [comment]
Word "Monarcy" as INPUT_WORD also failed. Same error.
